# Generated by Django 5.2.3 on 2025-06-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_image_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, help_text='The image url of the category', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='The name of the category', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='The description of the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, help_text='The image url of the course', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='The title of the course', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(help_text='The correct answer of the question', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(help_text='The difficulty of the question', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(help_text='The options of the question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='selected',
            field=models.CharField(blank=True, help_text='The selected answer of the question', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='The text of the question'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='The date and time the quiz session completed', null=True),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='score',
            field=models.IntegerField(default=0, help_text='The score of the quiz session'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='stars',
            field=models.IntegerField(default=0, help_text='The stars of the quiz session'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the quiz session started'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='The title of the video', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='transcript',
            field=models.TextField(blank=True, help_text='The transcript of the video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(help_text='The url of the video'),
        ),
    ]
