# Generated by Django 5.2.3 on 2025-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='is_quiz_generated',
            field=models.BooleanField(default=False, help_text='Whether the quiz is generated'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='is_quiz_submitted',
            field=models.BooleanField(default=False, help_text='Whether the quiz is submitted'),
        ),
    ]
